### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by happysalada** [sasa1977/site_encrypt#13]
I followed all the steps detailed in the readme. (in the logs I didn't use foo.bar, but I don't think it matters)
Looking at the logs, everything seems to be working well
```
0:38:00.497 [info] Running local ACME server at port 4002
20:38:00.611 [info] Running UnionWeb.Endpoint with Cowboy using http://0.0.0.0:4000
20:38:00.640 [debug] Starting Elixir.Union.DBListener with channel subscription: creation, update
20:38:00.645 [info] starting the job
Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex [ :: 1] > 20:38:02.137 request_id=2lann2j4effdgn9df8005c61 [info] GET /.well-known/acme-challenge/CO2f4Xdh2c0htpmRL_memw
20:38:02.138 request_id=2lann2j4eif40vu11o005ca3 [info] GET /.well-known/acme-challenge/CO2f4Xdh2c0htpmRL_memw
20:38:02.138 request_id=2lann2j4effdgn9df8005c61 [info] Sent 200 in 91µs
20:38:02.138 request_id=2lann2j4eif40vu11o005ca3 [info] Sent 200 in 125µs
clean-webpack-plugin: /Users/Raphael/Documents/Projects/gillithekid/union/priv/static has been removed.

webpack is watching the files…

20:38:11.807 [info] Saving debug log to /Users/Raphael/Documents/Projects/gillithekid/union/_build/dev/lib/union/priv/certbot/log/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing
/Users/Raphael/Documents/Projects/gillithekid/union/_build/dev/lib/union/priv/certbot/config/renewal/union.software.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator webroot, Installer None
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for localhost
Waiting for verification...
Cleaning up challenges

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed without reload, fullchain is
/Users/Raphael/Documents/Projects/gillithekid/union/_build/dev/lib/union/priv/certbot/config/live/union.software/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Congratulations, all renewals succeeded. The following certs have been renewed:
  /Users/Raphael/Documents/Projects/gillithekid/union/_build/dev/lib/union/priv/certbot/config/live/union.software/fullchain.pem (success)
```

however when I try to connect to https://localhost:4001 I get "unable to connect". It doesn't seem it's even trying to make the connection, it comes back instantly with that error.
for information I use
(elixir 1.7.3, erlang 21.0.9, phoenix 1.3.4)

(with the log level of debug, nothing logs in. That would mean it's not even going through phoenix)
Looking at the readme, port 4001 is used for https. I don't understand where something is started on that port. Maybe I missed something.
I understand you are busy, if you have a couple of pointers that would be awesome.

additional info: I am not setting anything particular variables on my dev environment. Let me know if there are more informations that could be useful

**Comment by sasa1977** [comment]
Are you maybe invoking `Mix.env` or some other `Mix` function directly from your runtime code? Keep in mind that `Mix` function can only be invoked at compile time. 

So for example, this is wrong and will fail at runtime:

```elixir
def foo do
  Mix.env()
end
```

To make it work, you need to invoke the `Mix` function during compilation:

```elixir
def foo do
  unquote(Mix.env())
end
```

That's one thing that comes to mind which could cause this problem. Otherwise, if you can give me some access to the code, I can try it out locally.

**Comment by happysalada** [comment]
You were right!
I wanted to not have to modify the code in dev, so I added a function ca_url taking mix.env as an argument
`ca_url: ca_url(unquote(Mix.env())),`

```
defp ca_url(:test), do: ""
defp ca_url(:dev), do: local_acme_server()
defp ca_url(:prod), do: "https://acme-staging-v02.api.letsencrypt.org/directory"
```

using unquote fixed that problem. I'm not too familiar with macros, now I understand why that unquote was there.

I have a new error in production
```

Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t: 08:56:39.712 [error] Error obtaining certificate for union.software:
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t: Traceback (most recent call last):
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:   File "/usr/bin/certbot", line 6, in <module>
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:     from pkg_resources import load_entry_point
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3086, in <module>
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:     @_call_aside
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:     f(*args, **kwargs)
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:     working_set = WorkingSet._build_master()
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:     return cls._build_from_requirements(__requires__)
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:     dists = ws.resolve(reqs, Environment())
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t:     raise VersionConflict(dist, req).with_context(dependent_req)
Sep 19 17:56:39 c1a13c6f1d67 union_web.1.0dh6pqwv5ltobcoh27b1lp16t: pkg_resources.ContextualVersionConflict: (idna 2.7 (/usr/lib/python2.7/site-packages), Requirement.parse('idna<2.7,>=2.5'), set(['requests'])) 
```
it seems to be a dependency problem, maybe because I am not using the edge repos like you are doing on your site. 
I will give that a go
(thanks again for the super fast response)

**Comment by sasa1977** [comment]
Unfortunately, I have no idea about certbot. You could try to work with Alpine 3.7 as I did on my blog, or otherwise try to make it work on 3.8.

As it seems that `site_encrypt` problems have been taken care of, I'll close this issue.

Wish you best of luck with compiling the final release!

**Comment by happysalada** [comment]
Ok for those interested. The problem actually was solved using the edge version of the repos. It seems that with the old version of certbot this bug appeared.

One question. In the readme, you don't mention much about the backup task for the certs (which is needed for production), would you be interested in a PR that adds that backup task to the readme?

**Comment by sasa1977** [comment]
> would you be interested in a PR that adds that backup task to the readme

What exactly did you have in mind here? The backup procedure is outside of scope of this project. I do have a brief mention of backup in the skeleton of the `config` module, inside the `handle_new_cert/0` function. What would you like to see added here?

**Comment by happysalada** [comment]
thinking about it, I agree with you, it's beyond the scope.
My original concern is that if you don't back up the certificate and you mistakenly deploy a new docker image with empty certs, then some bugs would happen.
Since backing up is not completely trivial, I thought it would be nice to have something about it.
But again, it will depend on which type of build is used and might vary a lot for each user, so I understand that it's out of scope.

Thanks a lot for all you help on this non-issue!
