### ISSUE TITLE
steps for restoring a backup

### ISSUE THREAD

**Issue by happysalada** [sasa1977/site_encrypt#16]
I have backed up the cert and certbot directory and I needed to deploy to a new machine.
I transfered both of those directories to the new machine. Now when running my image, I get the following error when the certs try to renew
```
[error] Error obtaining certificate for forunion.com:
CertStorageError: expected /opt/app/lib/union-0.3.8/priv/certbot/config/live/forunion.com/cert.pem to be a symlink
```
should I remove the content of the certbot folder and just keep the cert folder?
(just wondering if you ever had to restore a backup)

**Comment by happysalada** [comment]
Perfect it worked like a charm! Thanks a lot.


If I had to do a PR, here is what I would write

# Restoring a backup

restore previous cert and certbot directories. In the certbot directory, there should be symlinks in the subdirectory `certbot/config/live/MY_DOMAIN/`. There should be 4 symlinks to 4 files (cert.pem, fullchain.pem, privkey.pem and chain.pem). If the symlinks are preserved you have nothing more to do. If they are not.
- go check into `certbot/config/archive/MY_DOMAIN/`
- you should see some files, at least cert1.pem fullchain1.pem, privkey1.pem and chain1.pem. They correspond to the initially issued certificate. If your certificate has been renewed, you will find also cert2.pem, fulllchain2.pem... You'll have to make the symlink between the latest of these files and the live directory. So go to `certbot/config/live/`
- type the following (if your certificate has been renewed, replace the 1 with the latest number you have)

```Shell
rm cert.pem chain.pem fullchain.pem privkey.pem
ln -s ../../archive/MY_DOMAIN/cert1.pem cert.pem
ln -s ../../archive/MY_DOMAIN/chain1.pem chain.pem
ln -s ../../archive/MY_DOMAIN/fullchain1.pem fullchain.pem
ln -s ../../archive/MY_DOMAIN/privkey1.pem privkey.pem
```

and you're good to go!

--- 

I would personally add that after the production section in the readme. Let me know if this is good for you and I can make a PR. (if you want to write it yourself, absolutely no problem on my part too)

**Comment by sasa1977** [comment]
Thanks for reporting back! Feel free to submit that text as a PR.
