### ISSUE TITLE
Upgrade telemetry to 1.0

### ISSUE THREAD

**Issue by dzfranklin** [sasa1977/site_encrypt#39]
With phoenix `1.6.0` I'm getting a dependency resolution error

```
Failed to use "telemetry" (version 1.0.0) because
  phoenix (version 1.6.0) requires ~> 0.4 or ~> 1.0
  phoenix_live_view (version 0.16.4) requires ~> 0.4.2 or ~> 1.0
  swoosh (version 1.5.0) requires ~> 0.4.2 or ~> 1.0
  telemetry_metrics (version 0.6.1) requires ~> 0.4 or ~> 1.0
  telemetry_poller (versions 0.5.0 and 0.5.1) requires ~> 0.4
```

I think this can be fixed by just upgrading the version of `telemetry` in `site_encrypt`'s `mix.exs`

> There are no changes in the 1.0.0 release - it marks the stability of the API.
https://hexdocs.pm/telemetry/changelog.html#1-0-0

(In the meantime I've resolved this by adding `{:telemetry, "~> 1.0", override: true}` to my deps list.)

**Comment by sasa1977** [comment]
I'm a bit confused, since `site_encrypt` doesn't directly depend on telemetry. Are you certain that `site_encrypt` causes this?

**Comment by sasa1977** [comment]
Oh, this reminds me I got a PR fixing this in parent a few months ago. So it looks like the solution would be to publish new parent to hex.
