### ISSUE TITLE
replacing openssl

### ISSUE THREAD

**Issue by sasa1977** [sasa1977/site_encrypt#6]
AcmeServer currently [uses openssl to generate CA keys and sign CSRs](https://github.com/sasa1977/site_encrypt/blob/bedeb5c34e434faaeea3fa4574bcfdc6742cfb86/lib/acme_server/crypto.ex). I think that Erlang has the required pieces to do this natively in `:public_key` and `:crypto` modules. Some work has already been done by [here](https://github.com/voltone/site_encrypt/tree/replace_openssl), but I'm not sure about the current state. @voltone, let me know if you get stuck, or can't find the time, and I'll see if I can make some progress myself.

**Comment by voltone** [comment]
For the first shot I took at this I just copied some code I had lying around, fixed it up and added it to SiteEncrypt.Crypto. But it got quite bloated, and that's before I completed support for ECDSA certificates.

So I decided to revive the package I took the code from in the first place. It needs a bit more work, but I hope to publish a first version in a couple of days. Then I'll be able to implement the Crypto module without all the `:public_key` record handling, and focus on the business logic needed for the ACME server.

**Comment by sasa1977** [comment]
Thanks! There's absolutely no rush with this. If you need some help, let me know.

**Comment by voltone** [comment]
Just to keep you updated on the progress: I think I have a stable public API to my X509 library now, at least for those modules on which `site_encrypt` would depend. I need to tie up a few loose ends and increase test coverage before I'm comfortable releasing it. Once it's out I can reduce SiteEncrypt.Crypto to maybe a dozen lines of straightforward API calls.

**Comment by sasa1977** [comment]
Thanks for the update, looking forward to see it integrated here!

**Comment by voltone** [comment]
I create PR #12, please have a look, but give me another day or so to review before you merge it :)

**Comment by voltone** [comment]
BTW, I did not implement a persistent CA: that might encourage people to add the CA certificate to their OS/browser trust store, which would be a bad idea because we can't keep the CA key safe. See my comment here: https://github.com/phoenixframework/phoenix/issues/2896#issuecomment-401623027

Issuing a self-signed certificate would be better from that perspective, but that's not possible with the Acme protocol. Using an ephemeral CA and key for each certificate request seems to be the next best thing.

**Comment by sasa1977** [comment]
resolved with #12
