### ISSUE TITLE
add typespecs

### ISSUE THREAD

**Issue by sasa1977** [sasa1977/site_encrypt#9]
There are some basic typespecs in place, but we need them in other modules. This also include internal modules. Only public functions should be specced.

**Comment by juhalehtonen** [comment]
Hey! I could have a look at this over the next day or two. I've already started looking into this a bit on my fork, but will get back to you once I'm closer to finishing up.

**Comment by juhalehtonen** [comment]
Just to verify before I advance any further, is there any specific preference as to how @type declarations should be used here? 

Based on the existing code (e.g. acme_server.ex), I'm seeing that while in some cases they're defined explicitly for more specific combinations of types (such as @type method :: :get | :head | :put | :post | :delete), sometimes they're used for only a very specific case (such as @type site :: String.t()).

**Comment by sasa1977** [comment]
Thanks, looking forward to it!

Re type, looking back, I think that `site` is maybe an overkill for a type, as well as e.g. `status` and `body`. Usually I introduce types for complex things, and sometimes for the simple things too if they are used in multiple places, or if I estimated that they add documentation value.

In any case, I suggest you just make a PR with some first attempt, whatever feels natural, and then we can sort it out during the review.

**Comment by sasa1977** [comment]
closed through #11
